import os
from dotenv import load_dotenv
load_dotenv()
DATABASE_URL=os.getenv('DATABASE_URL')
SECRET_KEY=os.getenv('SECRET_KEY','change-me')
MERCADOPAGO_ACCESS_TOKEN=os.getenv('MERCADOPAGO_ACCESS_TOKEN')
MERCADOPAGO_PUBLIC_KEY=os.getenv('MERCADOPAGO_PUBLIC_KEY')
R2_ACCESS_KEY_ID=os.getenv('R2_ACCESS_KEY_ID')
R2_SECRET_ACCESS_KEY=os.getenv('R2_SECRET_ACCESS_KEY')
R2_BUCKET_NAME=os.getenv('R2_BUCKET_NAME')
R2_ENDPOINT_URL=os.getenv('R2_ENDPOINT_URL')
OPENROUTER_API_KEY=os.getenv('OPENROUTER_API_KEY')
ALGORITHM='HS256'
ACCESS_TOKEN_EXPIRE_MINUTES=30
